# 豆瓣 Z-Library 同步工具配置文件

# 豆瓣配置
douban:
  # 豆瓣用户 ID
  user_id: "your_douban_user_id"
  # 豆瓣 Cookie，用于登录
  cookies:
    bid: "your_bid_cookie"
    dbcl2: "your_dbcl2_cookie"
    ck: "your_ck_cookie"
  # 最大获取书籍数量
  max_books: 100
  # 请求延迟（秒）
  request_delay: 2.0

# 数据库配置
database:
  # 数据库类型: sqlite, mysql, postgresql
  type: "sqlite"
  # SQLite 数据库文件路径
  path: "db/douban_zlib.db"
  # MySQL/PostgreSQL 配置（如果使用）
  host: "localhost"
  port: 3306
  username: "username"
  password: "password"
  database: "douban_zlib"

# Calibre 配置
calibre:
  # Calibre Content Server URL
  server_url: "http://localhost:8080"
  # 用户名
  username: "username"
  # 密码
  password: "password"
  # 匹配阈值（0.0-1.0，值越高要求匹配度越精确）
  match_threshold: 0.6

# Z-Library 配置
zlibrary:
  # Z-Library 账号
  email: "your_email@example.com"
  # Z-Library 密码
  password: "your_password"
  # 下载目录
  download_dir: "data/downloads"
  # 首选格式（按优先级排序）
  preferred_formats:
    - "epub"
    - "mobi"
    - "pdf"
    - "azw3"
    - "djvu"

# 调度配置
schedule:
  # 调度类型: daily, weekly, interval
  type: "daily"
  # 每日执行时间（HH:MM 格式）
  at: "02:00"
  # 每周执行日期（0-6，0=周一）
  day: 0
  # 间隔小时数（仅在 type=interval 时使用）
  hours: 12
  # 间隔分钟数（仅在 type=interval 且 hours=0 时使用）
  minutes: 0

# 飞书通知配置
lark:
  # 是否启用飞书通知
  enabled: false
  # 飞书机器人 Webhook URL
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/your-webhook-token"
  # 飞书机器人安全设置中的签名密钥（可选）
  secret: ""

# 日志配置
log:
  # 日志目录
  log_dir: "logs"
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_level: "INFO"
  # 日志文件最大大小（MB）
  max_size_mb: 10
  # 保留日志文件数量
  backup_count: 5
  # 日志保留天数
  retention_days: 30

# 系统配置
system:
  # 临时目录
  temp_dir: "data/temp"
  # 是否在启动时清理临时文件
  cleanup_on_start: true
  # 是否在退出时清理临时文件
  cleanup_on_exit: false